### ISSUE TITLE
CLE 2.x - Requirements

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1545]
- [x] Data model for Projects - assignment - submission flow #1251
- [x] Add ability to filter assignments by project id on `/api/v1/cle/assignments`
- [x] Remove assignment body field on `/api/v1/cle/assignments` #1554 
- [x] activate the create endpoints for the correct POST data fields for each type #1539 
- [x] Give me the project / assignment hierarchies / below a certain level
- [x] only show responses from student / instructor / TA roles (by default)
- [x] Students should be able to edit there submissions past due date. #1141
- [x] Don't show submit assignment button if the assignment is not open #1142
