### ISSUE TITLE
2020, the roadmap.

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#181]
"The year is 2020, the session." was the first public discussion of some of the concepts that plan to power elmsln for the next decade of development into [The age of spiritual machines
](https://en.wikipedia.org/wiki/The_Age_of_Spiritual_Machines). 2020, at the time of this writing, is still far enough away that these concepts should not be upsetting to those currently working on solving them. We all still do stuff, we just want to routinize and eliminate the boring parts of what we all do we can tackle bigger instructional challenges and transform as many lives as possible.

“I think there is great value in perfecting technologies that set out to eliminate the webmaster, the developer, and the designer.” - Dries Buytaert - 2007 http://buytaert.net/drupal-and-eliminating-middlemen

Applying Dries' line to educational technology, what can we do to eliminate the sys admin, developer, drupal site builder, instructional designer, IDA and other roles that currently reside between the Student and Instructor in the development and delivery of high quality instruction. As part of this we need to optimize the body field via HAX, create intelligent agents that suggest course structures, automatically setup systems based on voice based suggestion data mine recommendations of sources to reference in courses, automate copyright management and presentation, capture, encode, and deliver media without setup concerns, transcribe media automatically, eliminate notions of "inaccessible" content through good design, and so on.

The most sustainable system is the one that the least humans interact with. Ask yourself constantly, how can we make this so someone else didn't need to know how it worked, it "Just Works" :tm: .

This is a much more philosophical roadmap then most are used to (a more typical one is in the wiki), but we also have been working on this for 8 years, are increasing in adoption and staffing, so these are the times to lay out vision.
- [ ] HAX - Headless Authoring experience; the elimination of the body / wysiwyg editor and creation of "course site tonight" type software. This eliminates notions of inaccessible, non-responsive layouts, and most issues that involve the need for a graphic artist / ida #85
- [ ] IDiA - Instructional Designer Intelligent Agents - Giving recommendations on how to structure courses based on both past courses as well as theory of successful instruction design strategies
- [ ] Tool Builder - Automation of the creation of original ideas for new tools in the network. Creating a GUI that does everything previously envisioned by btopro. #26 and #60
- [ ] Automatic course research engine - Lee Giles is doing some pretty awesome sounding automatic OER course topic generation based on minimal user input types of AI. It would be worth investing in integration with this if open source or at the very least finding something emergent to provide the same capabilities. http://coil.psu.edu/blog/building-online-books-using-open-educational-resources-for-zero-cost-personalized-and-collaborative-learning/
- [ ] Online University Schema - The templating of the automatic generation of an entirely university's infrastructure on the web, mirroring the structure of the template passed in. This would allow for the formation of new universities and online arms of existing universities to mirror the desires of these architects without the need to understand the technology involved. https://github.com/elmsln/online-university/issues/1

This is for

**Comment by michael-collins** [comment]
Sungug (http://snugug.com/musings/yo-dawg-i-heard-you-like-redesigns/) uses markdown on github, that when changed affects the automatic deployment of a site's hierarchy and structure, including content types. What if someone could alter markdown of an online university schema, and have that be what drives the creation of the system? You then begin to remove the developer from the workflow.

**Comment by btopro** [comment]
Not finished, never finished but these tasks have been broken out into actionable items and we both blog elsewhere instead of ranting here :)
