### ISSUE TITLE
CLE 2.x enhancements

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1816]
Continued list from #1545 

- [x] Make "Submission" form show details of the assignment this is being created for (title for now works)
- [x] Student Name #1835
- [x] Escape key should close modals
- [x] prevent angular blocking flyouts from loading
- [x] Layout design idea #1764
- [x] uploading multiple images #1781\
- [x] source button in wysiwyg #1774
- [x] Submissions endpoint needs to be able to take query params for assignment ID, User ID, section id, number of results (default is 10)
- [ ] All endpoints to provide "page" headers in a standard format (1st, last, previous, next urls)
- [ ] Add 'closed' tag to critiques on cle_dashboard #1139
- [ ] Pair off: Partner Critique #1274 
- [ ] Add Emoji studio reactions #1490 
- [ ] Sidecomments.js #322

**Comment by btopro** [comment]
outdated and many things found their way in.
