### ISSUE TITLE
Hit List to 0.1.0

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#196]
- [x] Accessibility / tab order of the Map icon and scrolling issue #190
- [ ] Video spacing issue (bandaid solution for now) #170 
- [ ] Icons being set that shouldn't be #197 
- [x] RESTws / D7.36 core issue #139

**Comment by btopro** [comment]
this is a meta issue so closing
