### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#215]
We need a visual for each point release / a thread that shows where we're heading and how far along we are. I think might be our best bet at a starting point is a visual that @michael-collins made awhile ago but need some clean up / visiting. This needs to visualize the state of every tool in the network and where things are heading (so even having greyed out the tools that we have planned that aren't there yet).

This way you can glance and make assessments like:
- Courses is very stable / needs clean up but is fundamentally working
- CIS UX wise is very unstable but functionality / architecture wise is very stable

Data for inclusion:
- Architecture
- User Experience
- Features

These can also be in order of priority, so if media is about to get priority it should be the 2nd thing listed even though CIS needs more UX love, etc. Assigning @heyMP since you guys are meeting today.

**Comment by michael-collins** [comment]
Styling Needs in order of importance

- [ ] Style options for images, videos, audio, media players
- [ ] WYSIWYG
- [ ] Tool bar button & icons
- [ ] Buttons and forms
- [ ] Icons, dropdowns, modals
- [ ] Page Layout (WYSIWYG) options  
- [ ] Navigation Patterns
- [ ] Cross tool actions (buttons and form embedding)
- [ ] Banner
- [ ] Eco Nav (section/role admin information)

**Comment by btopro** [comment]
System needs in order of importance (system, not initiatives like HAX). this doesn't mean it'll all happen in this order as you know we bounce around to whatever can be drilled into at any given time.

- CLE, Editorial and Discuss will all see major feature enhancements in the coming weeks as they all were recently implemented for a production course (then features / profiles updated to backport those improvements)
- Media - The items from the comment above at some level involve this. #96 
- ECD - #145  , this will require #71 and #212 which CIS needs to do really heavy lifting
- CPR - #165 , this will require #106 which can then be used to inform inbox / all systems. This also is important for handling profile type functionality
- Inbox - #76 , this will allow notifications, calendaring and messaging for all systems #220 . It also is a logical place for notifications from #101 #120 
- CIS - #40 , UX overhaul / dashboard fo controlling everything and making sense of it all. The bulk of the systems don't need to be done for this to really shine but they do at least need to be set in motion w/ some basic data models in order to make the mock ups functional (and if they aren't functional, what's the point)

**Comment by michael-collins** [comment]
Is there a list of acronym definitions somewhere?

**Comment by michael-collins** [comment]
Is there a list of acronym definitions somewhere?

**Comment by michael-collins** [comment]
Interestingly, the order of importance for the usability of the system requires almost the exact opposite of that list. Not sure how to reconcile that.

**Comment by michael-collins** [comment]
The style guide should solve some UX issues in parallel to your development list.

**Comment by btopro** [comment]
@michael-collins works really well actually, you constantly feel like you can't keep up with designing experience for new functionality, I'm not focusing on the things that the UX team will be tackling so they might be static long enough to stlye ;)

**Comment by heyMP** [comment]
Start of the ELMSLN style guide: https://cdn.rawgit.com/heyMP/elmsln/master/core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/index.html

This will allow us to more rapidly collaborate and build UI elements while maintaining consistency of our look and feel.

**Comment by michael-collins** [comment]
@heyMP I've started the CIS course dashboard interface per my mockups. Need help with jquery for triggering the horizontal tabs: http://codepen.io/michael-collins/pen/JYWBvP

Mockup from Slack UX Channel:
https://elmsln.slack.com/?redir=%2Ffiles%2Fcollins%2FF06NCEC7J%2Fscreen_shot_2015-06-23_at_4.17.22_pm.png

**Comment by michael-collins** [comment]
@heyMP Apparently you can nest tabs afterall. This didn't work the last time I tried to do it. However, I apparently did it wrong, you can nest them as I just discovered. I'll have to rebuild this.

**Comment by michael-collins** [comment]
@heyMP Okay, rebuilt it using proper tab nesting, so no need for jQuery.

**Comment by btopro** [comment]
<3
Ok, let's try this again. @heyMP , I DO NOT want you to stay up all night implementing this.

... looks awesome mike

**Comment by michael-collins** [comment]
@heyMP @btopro It's not perfect as I didn't have time to apply all of the styles that I wanted and it uses Zurb's icon font, but I think if we can get some of the functionality working, the CIS will be miles ahead of where it is now. Making a new course section should not be something users are confused about...

**Comment by btopro** [comment]
this issue related to making a roadmap which is largely out of date / we've been cranking through the issues in here the last several months; we'll need a new roadmap but done in the docs section instead of here (which there is a starting point of one there). Going to take the codepen for CIS and move it out to its own CIS UX issue
