### ISSUE TITLE
Outline designer 3.x wishlist

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#355]
Outline designer is in need of an overhaul for the 3.x version. This thread is to track features to add and ideas associated with this.
- [x] make a OD YAML submodule that can ingest a READ THE DOCS style outline structure and turn it into nodes
- [x] drop AJAX reloading #294 
- [x] OD git - hook outline pages / structure up to a READTHEDOCS style repo
- [x] Refactor / redo entire code base to be book specific off the API
- [ ] gitgutter style left column to glance and see whats changed
- [ ] allow for reusable structures that are pedagogically focused
- [ ] Automatically create systems, settings, content, media, assignments, and other things off of this setup routine. this is the course. Could also set waypoints and other XAPI capable spaces #160 
- [ ] Abstract the drag and drop / keyboard accessible aspect of HAX so that we can repurpose this UX across this and future systems
- [ ] Make an outline creation console that's separate from OD so that you can mock up and quickly build structures; this will allow for OD to be used in CIS to drive the creation of everything #232 
- [ ] ability to dictate how navigation downstream is rendered (flat list, steps to completion, full hierarchy, none {default}) specific to elmsln
- [ ] ability to append link type to everything below (related links); specific to elmsln
- [ ] Outline Designer 3.x / Types revisited #160

**Comment by michael-collins** [comment]
@btopro What is an outline creation console? Is that something similar to what I have in the mockups, with the batch create feature? Or is it more like a command line interface for creating?

**Comment by btopro** [comment]
OD but without making outline / editing nodes; more like just using the structuring capability and it being disconnectable from a backend. this would like you build out a site outline in a place different from where it would be deployed. Or could use it as a stand alone to build an outline visually, flip over to YAML mode and copy and paste the structure into a git repo. just flexibility

**Comment by btopro** [comment]
from prev thread worth noting:

human capacity, this is a good goal for capabilities in Outline Designer 3.x because I feel like that's what your creating needs for in. 2.x (the current version) can't possibly be worth adding these things into given how stable / little context it has of what we're doing, these connotations would provide API bending / breaking in that project. A thread that all these ideas get related to here for Outline Designer 3.x would probably be the way to go with a bulleted list of desires for it.

We'd want to query available options with this "reference page", ask where it lives, then query / auto complete and on save store the correct remote (or hell, local) piece of content so that it can be updated remotely as well as allow for the breaking connotation.

"Breaking" would basically be a workflow thing where
- [ ] content type changes to a page
- [ ] content from the remote (or local) address is loaded up in a rendered state then injected locally into the node that's being changed to a page content type
- [ ] heavy cache clearing cause this could be evil (content type switching is something that outline designer allows, not drupal nessecarily :) )

Like the idea, we've had remote page in the queue for awhile, the token / copy and paste step could be a good bridge to this later ease of use.

**Comment by btopro** [comment]
this is a haxcms discussion
