### ISSUE TITLE
Library_CDN implementation for ELMSLN_CDN Module

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#942]
A few tasks that will have to be taken care of in order to hook up the Library_CDN module with the ELMSLN_CDN module. 

- [x] Download and install Library_CDN & Dependencies.
- [x] Test that the Library & Dependencies do not brick the system.
- [x] Try to use jsdeliver to serve content
- [x] Extend the ELMSLN_CDN module to use the API in Library_CDN to make its local and remote CDN calls.
- [x] Extend the ELMSLN_CDN module to have a checkbox to ENABLE / DISABLE / LOCAL / REMOTE handle its files via the CDN
- [ ] ~~Fix CDNJS & JSDelivr CSS errors~~ #994 (will be fixed and supported in this module)
- [ ]  get Header add Access-Control-Allow-Origin "*" support if needed based on remote jquery making ajax calls
- [ ] write and implement the new easyCDN module to take care of CDN & library loading (#994)
- [ ] Need to update library_info hook because of #996.

#680 
#405

**Comment by mmilutinovic1313** [comment]
https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md

**Comment by btopro** [comment]
it's getting there but boatloads of errors still
- pull latest to your local, I cleaned up a few things
- then got a ton of errors though annyang is rewriting correctly against the non-china CDN location

```
Notice: Undefined index: data in advagg_js_alter() (line 914 of /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/advagg/advagg.module).
Notice: Undefined index: group in advagg_mod_sort_css_js() (line 1779 of /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/advagg/advagg_mod/advagg_mod.module).
Notice: Undefined index: group in advagg_mod_sort_css_js() (line 1780 of /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/advagg/advagg_mod/advagg_mod.module).
Notice: Undefined index: every_page in advagg_mod_sort_css_js() (line 1782 of /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/advagg/advagg_mod/advagg_mod.module).
Notice: Undefined index: weight in advagg_mod_sort_css_js() (line 1785 of /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/advagg/advagg_mod/advagg_mod.module).
Notice: Undefined index: weight in advagg_mod_sort_css_js() (line 1786 of /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/advagg/advagg_mod/advagg_mod.module).
Notice: Undefined index: weight in advagg_drupal_sort_css_js_stable() (line 3985 of /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/advagg/advagg.module).
Notice: Undefined index: group in advagg_drupal_sort_css_js_stable() (line 3986 of /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/advagg/advagg.module).
Notice: Undefined index: every_page in advagg_drupal_sort_css_js_stable() (line 3986 of /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/advagg/advagg.module).
Notice: Undefined index: data in advagg_mod_sort_css_js() (line 1821 of /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/advagg/advagg_mod/advagg_mod.module).
Notice: Undefined index: data in advagg_mod_sort_css_js() (line 1822 of /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/advagg/advagg_mod/advagg_mod.module).
Notice: Undefined index: data in advagg_mod_sort_css_js() (line 1826 of /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/advagg/advagg_mod/advagg_mod.module).
Notice: Undefined index: data in advagg_mod_sort_css_js() (line 1826 of /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/advagg/advagg_mod/advagg_mod.module).
```

**Comment by mmilutinovic1313** [comment]
Need to update library_info hook because of #996.

**Comment by mmilutinovic1313** [comment]
Do we want to close this out as this is kind of a duplicate of #994. Minus the:

" get Header add Access-Control-Allow-Origin "*" support if needed based on remote jquery making ajax calls" section

**Comment by btopro** [comment]
how about add " get Header add Access-Control-Allow-Origin "*" support if needed based on remote jquery making ajax calls" section over there and close this out

**Comment by mmilutinovic1313** [comment]
Sounds good - Added it to that issue. Will break some of the tasks for app creation out to smaller tasks to measure progress!
